(function(){var a=$j;a(document).ready(function(){a("html, body").addClass("js");var b=a("#baffinBrandSearch");b.length>0&&z.defaultText("#baffinBrandSearch",b.attr("value"))})})();
z.HeroGallery=function(a,b){if(!(this instanceof z.HeroGallery))return new z.HeroGallery(a,b);this.options=$j.extend({},z.HeroGallery.defaults,b);this.switchIdentifier="heroControlSwitch-";this.overlayIdentifier="heroControlOverlay-";this.labelIdentifier="heroControlLabel-";this.container=$j(a);this.images=$j("a",this.container);this.currentImage=0;this.switches=[];this.switchOverlays=[];$j("a.heroAlternate",this.container).css({opacity:0});this.images.css({position:"absolute"});this.container.css({height:this.container.find("a:eq(0)").innerHeight(),
overflow:"hidden"});this.setupControlPanel();this.switchesLength=this.switches.length;this.transitionThroughImage()};z.HeroGallery.defaults={waitDuration:3500,transitionDuration:1E3,pageTitle:"Hero Gallery"};
z.HeroGallery.prototype={setupControlPanel:function(){var a=[],b=this;a.push('<div id="heroControlPanel">');for(var c=0,e=b.images.length;c<e;c++)a.push('<div id="',b.switchIdentifier,c,'" class="heroControlSwitch">','<div id="',b.overlayIdentifier,c,'" class="heroControlSwitchOverlay" style="display:none; width:0px;"></div>','<span id="',b.labelIdentifier,c,'" class="heroControlSwitchLabel">',(c+1).toString(),"</span>","</div>");a.push("</div>");b.container.append(a.join(""));b.switches=$j("#heroControlPanel > div");
b.switchOverlays=$j("div",b.switches);$j("#heroControlPanel").click(function(d){if(d.target.id!="heroControlPanel"){d=d.target.id.replace(b.switchIdentifier,"").replace(b.overlayIdentifier,"").replace(b.labelIdentifier,"");var f="Slideshow-Stop-"+(parseInt(d)+1)+"-"+b.images[d].firstChild.alt;_gaq.push(["pageTrackerPriTr._trackEvent",b.options.pageTitle,"Promos",f]);b.cancelAll();b.switchImages(b.currentImage,d);b.switches[d].className="heroControlSwitch heroControlSwitchActive"}})},transitionThroughImage:function(){var a=
this;if(a.switchesLength>0){a.switches[a.currentImage].className="heroControlSwitch heroControlSwitchActive";a.switchOverlays[a.currentImage].style.display="block";a.switchOverlays[a.currentImage].style.webkitAnimationName="overlayTransition";a.switchOverlays[a.currentImage].style.webkitAnimationDuration=[a.options.waitDuration/600,"s"].join("");a.switchOverlays[a.currentImage].style.webkitAnimationTimingFunction="linear";a.timeout=setTimeout(function(){a.switchOverlays[a.currentImage].style.display=
"none";a.switches[a.currentImage].className="heroControlSwitch";a.switchImages(a.currentImage,a.currentImage+1);a.transitionThroughImage()},a.options.waitDuration)}},switchImages:function(a,b){var c=this;if(a!=b){if(b>=c.images.length)b=0;$j(c.images[a]).animate({opacity:0},{duration:c.options.transitionDuration,complete:function(){c.images[a].style.display="none"}});c.images[b].style.display="inline";$j(c.images[b]).animate({opacity:1},{duration:c.options.transitionDuration});c.currentImage=b}},
cancelAll:function(){clearTimeout(this.timeout);for(var a=0,b=this.switches.length;a<b;a++)this.switches[a].className="heroControlSwitch";a=0;for(b=this.switchOverlays.length;a<b;a++){this.switchOverlays[a].style.display="none";this.switchOverlays[a].style.width="0px"}}};z.LandingPage={};z.GridSelector=function(a,b){if(!(this instanceof z.GridSelector))return new z.GridSelector(a,b);this.init(a,b)};
z.GridSelector.prototype={init:function(a,b){this.gridSelectorWrap=a=jQuery(a);this.options=jQuery.extend({},{duration:1200,imagesPerRow:3,easing:"swing"},b);this.options.duration*=1;this.options.imagesPerRow*=1;this.intro=true;this.prefixThumbLen=18;this.prefixThumb="gridSelectorThumb_";this.padding=10;this.lastClientX=0;this.attachEvents()},initLazy:function(){var a=this.gridSelectorWrap;this.gridSelector=a.find("div.gridSelector");this.gridSelectorInner=this.gridSelector.find("div.gridSelectorInner");
this.mainThumbs=a.find("div.main_thumbs");this.mainThumbsInner=a.find("div.main_thumbs_inner");this.introImage=a.find("div.intro");this.bigImages=this.gridSelector.find("img");this.gridSelectorInner.width((this.bigImages.eq(0).width()+this.padding)*this.options.imagesPerRow+this.padding+5);this.mainThumbs.width(a.width());this.gridSelectorOffsetLeft=a.offset().left;this.mainThumbsWidth=this.mainThumbs.width();this.mainThumbsHalfWidth=Math.floor(this.mainThumbsWidth/2);this.halfStep=Math.floor(this.options.duration/
2)},scrollToFullsizeImage:function(a){a=this.bigImages[a.substr(this.prefixThumbLen)];this.gridSelectorInner.stop();this.gridSelectorInner.animate({left:a.offsetLeft*-1,top:a.offsetTop*-1},{easing:this.options.easing,duration:this.options.duration})},introTransition:function(){if(this.intro){jQuery(this.introImage).find("img").animate({opacity:"hide"},this.halfStep);this.introThumbImages=this.gridSelectorWrap.find("ul.intro_thumbs img");this.mainThumbsInner.width((this.introThumbImages.eq(1).width()+
this.padding)*this.introThumbImages.length+this.padding);this.mainThumbs.height(this.introThumbImages.eq(1).height());this.mainThumbsInner.slideDown(this.halfStep);this.mainThumbs.find("div.actionArrow").fadeIn(this.halfStep);this.intro=false}},inverseScrollMainThumbs:function(a){var b=(this.mainThumbsWidth-this.mainThumbsInner.width())/this.mainThumbsWidth;b=Math.floor((a-this.gridSelectorOffsetLeft)*b);this.lastClientX=a;this.mainThumbsInner.stop().css("left",b)},transitionToPos:function(a,b){var c=
(this.mainThumbsWidth-this.mainThumbsInner.width())/this.mainThumbsWidth;c=Math.floor((a-this.gridSelectorOffsetLeft)*c);this.mainThumbsInner.stop().animate({left:c},250,function(){b()})},attachEvents:function(){var a=this,b,c;jQuery(this.gridSelectorWrap).bind("mousedown",function(e){e.button===0&&e.preventDefault()});jQuery(document.body).bind("click",function(e){if(a.intro){a.initLazy();a.mainThumbs.bind("mouseenter",function(d){if(!a.userKnowsToScroll){a.gridSelectorWrap.find(".actionArrow").fadeOut();
a.userKnowsToScroll=true}c=function(){a.inverseScrollMainThumbs.call(a,d.clientX);a.mainThumbs.bind("mousemove",function(f){a.inverseScrollMainThumbs.call(a,f.clientX)})};Math.abs(d.clientX-a.lastClientX)>6?a.transitionToPos.call(a,d.clientX,function(){c()}):c()});a.mainThumbs.bind("mouseleave",function(){a.mainThumbs.unbind("mousemove")})}b=e.target.id;if(typeof b!=="string"){console.warn("target id not a string.");console.trace()}if(b.indexOf(a.prefixThumb)!==-1){e.preventDefault();a.intro&&a.introTransition.call(a);
a.scrollToFullsizeImage.call(a,b)}})}};